services:
  api:
    image: ibabiankou/home-lab:narrator-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      PYTHONUNBUFFERED: yes
      PG_URL: postgresql://narrator:narrator@pg:5432/narrator
      OL_PG_URL: postgresql://narrator:${NN_PG_PWD}@pgpool.mng.ggnt.eu:5432/openlibrary
      S3_ENDPOINT: http://s3:4566
      S3_ACCESS: test
      S3_SECRET: test
      KOKORO_BASEURL: http://speech:8001
      RMQ_HOST: rmq
      RMQ_PORT: 5672
      RMQ_USERNAME: narrator
      RMQ_PASSWORD: narrator
      SPEECH_GENERATION_INTERVAL_SEC: 5
      KC_CLIENT_ID: ${KC_CLIENT_ID}
      KC_CLIENT_SECRET: ${KC_CLIENT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
    depends_on:
      pg:
        condition: service_healthy
        restart: true
      s3:
        condition: service_healthy
        restart: true
      rmq:
        condition: service_healthy
        restart: true
      speech:
        condition: service_started
        restart: true
      imgnginx:
        condition: service_started
        restart: true
    ports:
      - "8000:8000"
  pg:
    image: postgres:17.7
    environment:
      POSTGRES_PASSWORD: narrator
      POSTGRES_USER: narrator
      POSTGRES_DB: narrator
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      retries: 5
    ports:
      - "5432:5432"
  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      retries: 5
    volumes:
      - "./scripts/init-s3.py:/etc/localstack/init/ready.d/init-s3.py"
      - "./volumes/s3:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  rmq:
    image: rabbitmq:4.2-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: narrator
      RABBITMQ_DEFAULT_PASS: narrator
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      retries: 5

  speech:
    image: ibabiankou/home-lab:narrator-speech
    build:
      context: .
      dockerfile: ./speech-generator/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PYTHONUNBUFFERED: yes
      S3_ENDPOINT: http://s3:4566
      S3_ACCESS: test
      S3_SECRET: test
      RMQ_HOST: rmq
      RMQ_PORT: 5672
      RMQ_USERNAME: narrator
      RMQ_PASSWORD: narrator
      AUDIO_FORMAT: ogg
      AUDIO_SUBTYPE: OPUS
      AUDIO_CONTENT_TYPE: audio/ogg
    depends_on:
      s3:
        condition: service_healthy
        restart: true
      rmq:
        condition: service_healthy
        restart: true


  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    command:
      - start-dev
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Ensures you can access it via localhost:8080
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      # Map your local themes folder to the Keycloak themes directory
      - ./keycloak-theme:/opt/keycloak/themes/nnarrator


  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:v3.31.3
    environment:
      IMGPROXY_USE_S3: "true"
      IMGPROXY_S3_ENDPOINT: "http://s3:4566"
      IMGPROXY_S3_ENDPOINT_USE_PATH_STYLE: "true"
      IMGPROXY_BASE64_URL_INCLUDES_FILENAME: "true"
      IMGPROXY_BASE_URL: "s3://narrator"
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_USE_LAST_MODIFIED: "true"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      IMGPROXY_KEY: ""
      IMGPROXY_SALT: ""
    ports:
      - "8081:8080"
    volumes:
      - "./volumes/imgnginx:/proxy_cache"
    depends_on:
      s3:
        condition: service_healthy
        restart: true


  imgnginx:
    image: nginxinc/nginx-unprivileged:1.29.8
    volumes:
      - "./volumes/imgnginx:/proxy_cache"
      - "./local-configs/imgnginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8082:8080"
    depends_on:
      imgproxy:
        condition: service_started
        restart: true


  streamer:
    image: ghcr.io/readium/readium:0.7.1
    command:
      - serve
      - --scheme
      - file
      - --file-directory
      - /epub
      - --address
      - 0.0.0.0
    volumes:
      - "./out/epub:/epub"
    ports:
      - "15080:15080"
